# Generated by Django 3.2 on 2023-01-10 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweeter', '0003_dislike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='title',
            new_name='text',
        ),
    ]
